#!/usr/bin/env bash
# Module: fancontrol
# DESC: fancontrol + config
# DEFAULT: on
# ORDER: 580
# Called by install-packages.sh orchestrator

install_fancontrol() {
    printf "${YELLOW}Installing fancontrol and config...\n${NC}"
    printf "${LCYAN}--------------------------------------------------------------------------------\n${LRED}"
    printf "Original copy of fancontrol config if exist is available in /etc/fancontrol.ORIGINAL\n"
    printf "New settings can be made with pwmconfig\n"
    printf "${LCYAN}--------------------------------------------------------------------------------\n${NC}"
    sudo apt-get -y install fancontrol


    printf "${YELLOW}Adding restart on failure to fancontrol service...\n${NC}"
    if [[ -f /lib/systemd/system/fancontrol.service ]]; then
        sudo cp /lib/systemd/system/fancontrol.service /lib/systemd/system/fancontrol.service.bak
        sudo sed -i '/\[Service\]/a Restart=on-failure\nRestartSec=5s' /lib/systemd/system/fancontrol.service
        sudo systemctl daemon-reload
    else
        printf "${RED}Fancontrol service file not found\n${NC}"
    fi

    printf "${YELLOW}Backup fancontrol config...\n${NC}"
    if [[ -f /etc/fancontrol ]]; then
        printf "/etc/fancontrol exists. Backup to /etc/fancontrol.ORIGINAL"
        sudo mv /etc/fancontrol /etc/fancontrol.ORIGINAL
    fi

    printf "${YELLOW}Generating new fancontrol config...\n${NC}"
    if [[ ${RELEASE_NUMBER} -le "20" ]]; then
        printf "${LCYAN}--------------------------------------------------------------------------------\n${PURPLE}"
        printf "Generating /etc/fancontrol files (Release number (less or equal): Mint 20) \n"
        printf "${LCYAN}--------------------------------------------------------------------------------\n${GREEN}"
        # ----> OUT mint20
        # #Configuration file generated by pwmconfig, changes will be lost
        # INTERVAL=10
        # DEVPATH=hwmon1=devices/platform/w83627ehf.656
        # DEVNAME=hwmon1=nct6775
        # FCTEMPS=hwmon1/device/pwm2=hwmon0/temp1_input hwmon1/device/pwm1=hwmon0/temp1_input
        # FCFANS=hwmon1/device/pwm2=hwmon1/device/fan2_input hwmon1/device/pwm1=hwmon1/device/fan1_input
        # MINTEMP=hwmon1/device/pwm2=20 hwmon1/device/pwm1=20
        # MAXTEMP=hwmon1/device/pwm2=60 hwmon1/device/pwm1=60MINSTART=hwmon1/device/pwm2=150 hwmon1/device/pwm1=30
        # MINSTOP=hwmon1/device/pwm2=0 hwmon1/device/pwm1=16
        sudo bash -c "echo -e '# Configuration file generated by pwmconfig, changes will be lost\nINTERVAL=10\nDEVPATH=hwmon1=devices/platform/w83627ehf.656\nDEVNAME=hwmon1=nct6775\nFCTEMPS=hwmon1/device/pwm2=hwmon0/temp1_input hwmon1/device/pwm1=hwmon0/temp1_input\nFCFANS=hwmon1/device/pwm2=hwmon1/device/fan2_input hwmon1/device/pwm1=hwmon1/device/fan1_input\nMINTEMP=hwmon1/device/pwm2=20 hwmon1/device/pwm1=20\nMAXTEMP=hwmon1/device/pwm2=60 hwmon1/device/pwm1=60MINSTART=hwmon1/device/pwm2=150 hwmon1/device/pwm1=30\nMINSTOP=hwmon1/device/pwm2=0 hwmon1/device/pwm1=16' >> /etc/fancontrol"
    elif [[ ${RELEASE_NUMBER} -ge "21" ]]; then
        printf "${LCYAN}--------------------------------------------------------------------------------\n${PURPLE}"
        printf "Generating /etc/fancontrol files (Release number (greater or equal): Mint 21) \n"
        printf "${LCYAN}--------------------------------------------------------------------------------\n${GREEN}"
        # ----> OUT mint21

        # New settings for Mint >=21 Asus P8Z77-V-LX2 Motherboard

        ####################################################
        # File: /etc/fancontrol.hwmon2
        ####################################################
        # # Configuration file generated by pwmconfig, changes will be lost
        # INTERVAL=15
        # DEVPATH=hwmon1=devices/platform/coretemp.0 hwmon2=devices/platform/nct6775.656
        # DEVNAME=hwmon1=coretemp hwmon2=nct6779
        # FCTEMPS=hwmon2/pwm1=hwmon1/temp1_input hwmon2/pwm2=hwmon1/temp1_input hwmon2/pwm3=hwmon1/temp1_input
        # FCFANS=hwmon2/pwm1=hwmon2/fan1_input hwmon2/pwm2=hwmon2/fan2_input hwmon2/pwm3=hwmon2/fan3_input
        # MINTEMP=hwmon2/pwm1=45 hwmon2/pwm2=30 hwmon2/pwm3=30
        # MAXTEMP=hwmon2/pwm1=75 hwmon2/pwm2=75 hwmon2/pwm3=75
        # MINSTART=hwmon2/pwm1=75 hwmon2/pwm2=150 hwmon2/pwm3=90
        # MINSTOP=hwmon2/pwm1=60 hwmon2/pwm2=0 hwmon2/pwm3=75
        # MINPWM= hwmon2/pwm3=75
        #
        # Note: hwmon1 is coretemp, hwmon2 is nct6779
        #       hwmon2/pwm1 is fan1, hwmon2/pwm2 is fan2, hwmon2/pwm3 is fan3
        #       hwmon1/temp1_input is the temperature sensor used for all fans (core package temperature)
        # Found the following devices:
        # hwmon1 is coretemp
        # hwmon2 is nct6779
        #
        # FAN PWM
        # hwmon2/pwm1
        # hwmon2/pwm2
        # hwmon2/pwm3
        sudo bash -c "echo -e '# Configuration file generated by pwmconfig, changes will be lost\nINTERVAL=15\nDEVPATH=hwmon1=devices/platform/coretemp.0 hwmon2=devices/platform/nct6775.656\nDEVNAME=hwmon1=coretemp hwmon2=nct6779\nFCTEMPS=hwmon2/pwm1=hwmon1/temp1_input hwmon2/pwm2=hwmon1/temp1_input hwmon2/pwm3=hwmon1/temp1_input\nFCFANS=hwmon2/pwm1=hwmon2/fan1_input hwmon2/pwm2=hwmon2/fan2_input hwmon2/pwm3=hwmon2/fan3_input\nMINTEMP=hwmon2/pwm1=45 hwmon2/pwm2=30 hwmon2/pwm3=30\nMAXTEMP=hwmon2/pwm1=75 hwmon2/pwm2=75 hwmon2/pwm3=75\nMINSTART=hwmon2/pwm1=75 hwmon2/pwm2=150 hwmon2/pwm3=90\nMINSTOP=hwmon2/pwm1=60 hwmon2/pwm2=0 hwmon2/pwm3=75\nMINPWM= hwmon2/pwm3=75' >> /etc/fancontrol.hwmon2"
        ####################################################
        # File: /etc/fancontrol.hwmon3
        ####################################################
        # # Configuration file generated by pwmconfig, changes will be lost
        # INTERVAL=15
        # DEVPATH=hwmon2=devices/platform/coretemp.0 hwmon3=devices/platform/nct6775.656
        # DEVNAME=hwmon2=coretemp hwmon3=nct6779
        # FCTEMPS=hwmon3/pwm1=hwmon2/temp1_input hwmon3/pwm2=hwmon2/temp1_input hwmon3/pwm3=hwmon2/temp1_input
        # FCFANS=hwmon3/pwm1=hwmon3/fan1_input hwmon3/pwm2=hwmon3/fan2_input hwmon3/pwm3=hwmon3/fan3_input
        # MINTEMP=hwmon3/pwm1=45 hwmon3/pwm2=30 hwmon3/pwm3=30
        # MAXTEMP=hwmon3/pwm1=75 hwmon3/pwm2=75 hwmon3/pwm3=75
        # MINSTART=hwmon3/pwm1=75 hwmon3/pwm2=150 hwmon3/pwm3=90
        # MINSTOP=hwmon3/pwm1=60 hwmon3/pwm2=0 hwmon3/pwm3=75
        # MINPWM= hwmon3/pwm3=75
        #    
        # Note: hwmon2 is coretemp, hwmon3 is nct6779
        #       hwmon3/pwm1 is fan1, hwmon3/pwm2 is fan2, hwmon3/pwm3 is fan3
        #       hwmon2/temp1_input is the temperature sensor used for all fans (core package temperature)
        # Found the following devices:
        # hwmon2 is coretemp
        # hwmon3 is nct6779
        #
        # FAN PWM
        # hwmon3/pwm1
        # hwmon3/pwm2
        # hwmon3/pwm3
        sudo bash -c "echo -e '# Configuration file generated by pwmconfig, changes will be lost\nINTERVAL=15\nDEVPATH=hwmon2=devices/platform/coretemp.0 hwmon3=devices/platform/nct6775.656\nDEVNAME=hwmon2=coretemp hwmon3=nct6779\nFCTEMPS=hwmon3/pwm1=hwmon2/temp1_input hwmon3/pwm2=hwmon2/temp1_input hwmon3/pwm3=hwmon2/temp1_input\nFCFANS=hwmon3/pwm1=hwmon3/fan1_input hwmon3/pwm2=hwmon3/fan2_input hwmon3/pwm3=hwmon3/fan3_input\nMINTEMP=hwmon3/pwm1=45 hwmon3/pwm2=30 hwmon3/pwm3=30\nMAXTEMP=hwmon3/pwm1=75 hwmon3/pwm2=75 hwmon3/pwm3=75\nMINSTART=hwmon3/pwm1=75 hwmon3/pwm2=150 hwmon3/pwm3=90\nMINSTOP=hwmon3/pwm1=60 hwmon3/pwm2=0 hwmon3/pwm3=75\nMINPWM= hwmon3/pwm3=75' >> /etc/fancontrol.hwmon3"
    else
        printf "${LCYAN}--------------------------------------------------------------------------------\n${LRED}"
        printf "Not generating /etc/fancontrol files (Release number: Not recognized) \n"
        printf "Try to generate new settings with pwmconfig\n"
        printf "${LCYAN}--------------------------------------------------------------------------------\n${GREEN}"
    fi

    # printf "${LCYAN}--------------------------------------------------------------------------------\n${LRED}"
    # printf "Adding hardware in /etc/modules: \n"
    # printf "${LCYAN}--------------------------------------------------------------------------------\n${GREEN}"
    # sudo bash -c "echo -e 'coretemp\nw83627ehf\nnct6775\n' >> /etc/modules"

    printf "${YELLOW}Fix kernel modules load order for fancontrol...\n${NC}"
    # Define the modules we are looking for (coretemp, nct6775) and the config file we want to write to
    # Note: nct6775 is the driver name for nct6779 chips
    MODULES=("coretemp" "nct6775", "asus")
    CONF_FILE="/etc/modules-load.d/fancontrol.conf"
    # Check if the config file already exists and back it up if it does
    if [[ -f "$CONF_FILE" ]]; then
        printf "${YELLOW}$CONF_FILE already exists. Backing up to $CONF_FILE.bak\n${NC}"
        sudo cp "$CONF_FILE" "$CONF_FILE.bak"
    fi
    # Check if the modules are present and compatible with the system, and collect the ones that are compatible
    FOUND_MODULES=()
    for mod in "${MODULES[@]}"; do
        # Check if the hardware supports the module
        # modprobe --dry-run checks if the module can be loaded
        if modprobe --dry-run "$mod" > /dev/null 2>&1; then
            printf "${GREEN}[MATCH] $mod is compatible with this system.${NC}\n"
            FOUND_MODULES+=("$mod")
        else
            printf "${RED}[SKIP]  $mod was not found or is not supported.${NC}\n"
        fi
    done
    # Check if any compatible modules were found and write them to the config file, or print a message if none were found
    if [ ${#FOUND_MODULES[@]} -eq 0 ]; then
        printf "${RED}No relevant modules found. Nothing to write.\n${NC}"
    else
        # Create or overwrite the configuration file
        printf "${YELLOW}Writing to $CONF_FILE...\n${NC}"
        {
            echo "# Generated by script to stabilize fancontrol hwmon indices"
            for mod in "${FOUND_MODULES[@]}"; do
                echo "$mod"
            done
        } | sudo tee "$CONF_FILE" > /dev/null
        printf "${GREEN}Done. Please reboot your system for the order to take effect.${NC}\n\n"
    fi

    printf "${LCYAN}--------------------------------------------------------------------------------\n${LRED}"
    printf "Please restart system and check fancontrol.service\n"
    printf "If service is not started run: sudo pwmconfig and follow the wizard\n"
    printf "${LCYAN}--------------------------------------------------------------------------------\n${GREEN}"
    read -n 1 -s -r -p "Press any key to continue"
    sleep 3
    printf "\n${NC}"
}
